name: CI/CD Pipeline

# Trigger this workflow on push to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define the jobs to run
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Set up Docker Buildx (for advanced Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Step 4: Build and push Flask API image
      - name: Build and push Flask API
        uses: docker/build-push-action@v4
        with:
          context: ./api-server-flask
          push: true
          tags: |
            tbains21/flask-api:latest
            tbains21/flask-api:${{ github.sha }}
          cache-from: type=registry,ref=tbains21/flask-api:latest
          cache-to: type=inline
      
      # Step 5: Build and push React UI image
      - name: Build and push React UI
        uses: docker/build-push-action@v4
        with:
          context: ./react-ui
          push: true
          tags: |
            tbains21/react-ui:latest
            tbains21/react-ui:${{ github.sha }}
          build-args: |
            REACT_APP_BACKEND_SERVER=http://localhost:5001/api/
          cache-from: type=registry,ref=tbains21/react-ui:latest
          cache-to: type=inline
      
      # Step 6: Print success message
      - name: Image push successful
        run: |
          echo "✅ Docker images successfully built and pushed!"
          echo "Flask API: tbains21/flask-api:latest"
          echo "React UI: tbains21/react-ui:latest"